# https://hub.docker.com/_/ubuntu
# The ubuntu:latest tag points to the "latest LTS"
image: ubuntu:latest

stages:
  - test

test:
  stage: test
  script:
  # https://rtfm.co.ua/en/docker-configure-tzdata-and-timezone-during-build/
  # https://askubuntu.com/a/1098881
  - export TZ=Asia/Taipei
  - ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  # https://stackoverflow.com/a/58072486
  - apt-get update
  - apt-get install -y wget make git gettext gcc
  - make clone_pali_data
  - make download_go
  # test common library for online/offline, dictionary/tipitaka
  - make test_lib
  # test dictionary
  - make test_dictionary
  # test tipitaka
  - make test_tipitaka
  # misc
  - make test_util
  only:
  - master
