language: go
go:
  - 1.12.17
  - 1.14.4
install:
- make clone_pali_data
- make install
script:
- make test_lib
- make test_twpo2cn
- make test_util
- make test_bookparser
- make test_wordparser
# test_triebuild must run before test_vfsbuild. Or ru-run test_wordparser
- make test_triebuild
- make test_vfsbuild
- make test_symlink
