language: go
go:
  - 1.12.17
  - 1.14.6
install:
- make clone_pali_data
- make install
script:
# test common library for online/offline, dictionary/tipitaka
- make test_lib
- make test_dictionary
- make test_vfsbuild
- make test_symlink
# misc
- make test_util
